kind: live
title: {{ cookiecutter.project_name }}

images:
  train:
    ref: image:/$[[ project.owner ]]/$[[ flow.project_id ]]:v1
    dockerfile: $[[ flow.workspace ]]/Dockerfile
    context: $[[ flow.workspace ]]/


jobs:
  train:
    image: $[[ images.train.ref ]]
    bash: |
      echo Put your training code here
